name: Preprocessing Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Preprocessing Script
      run: |
        python preprocessing/automate_Rijal_Akhdan.py

    - name: Check Preprocessed Folder
      run: |
        echo "Cek isi folder preprocessing:"
        ls -R preprocessing